version: '3'

services:

  mariadb:
    container_name: mydb
    image: mariadb
    pull_policy: never
    build: ./requirements/mariadb/
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PW}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - ${MY_NETWORK}

  wordpress:
    depends_on:
      - mariadb
    container_name: mywp
    image: wordpress
    pull_policy: never
    build: ./requirements/wordpress/
    restart: always
    expose:
      - "9000"
    env_file: .env
    volumes:
      - wp-vol:/var/www/html
    networks:
      - ${MY_NETWORK}

  nginx:
    depends_on:
      - mariadb
    container_name: mynginx
    image: nginx
    pull_policy: never
    build: ./requirements/nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - wp-vol:/var/www/html
    networks:
      - ${MY_NETWORK}

networks:
  mynet:
    name: ${MY_NETWORK}

volumes:
 wp-vol:
  driver: local
  driver_opts:
    o: bind
    type: none
    device: ${WP_WWW_PATH}