version: '3'

services:

  mariadb:
    container_name: mydb
    image: mariadb
    pull_policy: never
    build: ./requirements/mariadb/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - MYSQL_PASSWORD=${MYSQL_PW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      - ${MYSQL_CONFIG_PATH}:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      - ${MY_NETWORK}

  wordpress:
    depends_on:
      - mariadb
      - nginx
    container_name: mywp
    image: wordpress
    pull_policy: never
    build: ./requirements/wordpress/
    restart: always
    environment:
      - WORDPRESS_DB_HOST=mydb
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=wp_
    volumes:
      - ${WP_WWW_PATH}:/var/www/html
    networks:
      - ${MY_NETWORK}

  nginx:
    container_name: mynginx
    image: nginx
    pull_policy: never
    build: ./requirements/nginx/
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${WP_WWW_PATH}:/var/www/html
    networks:
      - ${MY_NETWORK}

networks:
  mynet:
    name: ${MY_NETWORK}
